In [26]:
# IMPORTING ALL REQUIRED LIBRARIES 
import pandas as pd
import numpy as np
import re
import nltk

## DATASET IMPORTED FOR THIS PROJECT IT HAVE 1 INPU COL & 1 OUTPUT

In [58]:
df=pd.read_csv('IMDB Dataset.csv')
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [59]:
df.shape

(50000, 2)

## AS WE CAN SEE FROM DF REVIEW COL WE HAVE FEW PROBLEMS 
1.HTML TEXT 
2.SPECIAL CHARACTERS 
3.SOFT WORDS NO USE IN OUR MODEL TRAINING
4.STEM WORDS

## TAKING 10000 ROWS ONLY AS DATASET IS VEY BIG & WAS TAKING VERY LONG TIME TO TRAIN

In [60]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

## RANDOM 10000 ROWS

In [61]:
df=df.sample(10000)
df

review sentiment
9571   This movie, with all its complexity and subtle...  positive
17463  Dolph Lundgren stars as Murray Wilson an alcoh...  negative
32417  "The Quickie" tells of a decadent Russian mob ...  negative
5827   This is so blatantly a made-for-TV ripoff of B...  negative
31252  For starters, I would like to say that I'm a f...  negative
...                                                  ...       ...
27876  Really. Does any week go by that Oprah doesn't...  negative
22244  Hello all! I went to this movie without any ex...  positive
27931  Excellent drama about 2 alienated, spoiled pun...  positive
10656  Seriously, I couldn't find anything that const...  negative
9668   Sherman Hemsley was great in the Jeffersons an...  negative

[10000 rows x 2 columns]

## ENCODING TARGET 🎯 COL  

In [62]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [63]:
df.sample(20)

review  sentiment
37099  Now I love American Pie 1 and 2 while 3 was gr...          1
1651   Okay,I had watched this movie when I was very ...          0
27619  This is the third parody of the scary movies a...          0
47426  No redeeming features, this film is rubbish. I...          0
956    Great premise, poor execution. Cast of great a...          0
10536  Dark Harvest 3: Scarecrow: 1 out of 10: In Ein...          0
11060  Ben Stiller doesn't so much act as react. And ...          0
16884  You got to go and dig those holes. Holes only ...          1
20243  When the movie was released it was the biggest...          0
35369  Oh God, Why? I am aghast at the sheer ineptitu...          0
32197  What I've seen of Wolfgang Petersen's films ha...          1
33688  This is the sort of unknown and forgotten film...          1
11811  When I watched L'Appartement with my girlfrien...          1
44857  This is said to be the first Polish western an...          0
20507  The information contained in this movie is som...          1
42593  Done in a mock-documentary style, late 60's su...          0
47160  This film could have been great- but wasn't. A...          0
9049   I ended up watching this movie before even goi...          0
21965  I say sadly because if you see this movie now,...          1
12365  Imagine a film the complete opposite of Lawren...          0

## A FUNC TO REMOVE HTML TAGS 

In [64]:
def remove_html(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,'',text)

In [65]:
#APPLYING THE FUNC
df['review']=df['review'].apply(remove_html)

In [66]:
df

review  sentiment
9571   This movie, with all its complexity and subtle...          1
17463  Dolph Lundgren stars as Murray Wilson an alcoh...          0
32417  "The Quickie" tells of a decadent Russian mob ...          0
5827   This is so blatantly a made-for-TV ripoff of B...          0
31252  For starters, I would like to say that I'm a f...          0
...                                                  ...        ...
27876  Really. Does any week go by that Oprah doesn't...          0
22244  Hello all! I went to this movie without any ex...          1
27931  Excellent drama about 2 alienated, spoiled pun...          1
10656  Seriously, I couldn't find anything that const...          0
9668   Sherman Hemsley was great in the Jeffersons an...          0

[10000 rows x 2 columns]

## A FUNC TO CONVERT TEXT TO LOWER CASE

In [67]:
def converttolower(text):
    return text.lower()

In [68]:
df['review']=df['review'].apply(converttolower)
df

review  sentiment
9571   this movie, with all its complexity and subtle...          1
17463  dolph lundgren stars as murray wilson an alcoh...          0
32417  "the quickie" tells of a decadent russian mob ...          0
5827   this is so blatantly a made-for-tv ripoff of b...          0
31252  for starters, i would like to say that i'm a f...          0
...                                                  ...        ...
27876  really. does any week go by that oprah doesn't...          0
22244  hello all! i went to this movie without any ex...          1
27931  excellent drama about 2 alienated, spoiled pun...          1
10656  seriously, i couldn't find anything that const...          0
9668   sherman hemsley was great in the jeffersons an...          0

[10000 rows x 2 columns]

## A FUNC TO REMOVE SPECIAL CCHARACTERS 

In [69]:
def special_char(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
    return x        

In [70]:
df['review']=df['review'].apply(special_char)

In [71]:
df

review  sentiment
9571   this movie  with all its complexity and subtle...          1
17463  dolph lundgren stars as murray wilson an alcoh...          0
32417   the quickie  tells of a decadent russian mob ...          0
5827   this is so blatantly a made for tv ripoff of b...          0
31252  for starters  i would like to say that i m a f...          0
...                                                  ...        ...
27876  really  does any week go by that oprah doesn t...          0
22244  hello all  i went to this movie without any ex...          1
27931  excellent drama about 2 alienated  spoiled pun...          1
10656  seriously  i couldn t find anything that const...          0
9668   sherman hemsley was great in the jeffersons an...          0

[10000 rows x 2 columns]

## STOPWORDS IN ENGLISH LANG.

In [72]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

## A FUNC TO REMOVE STOPWORDS

In [73]:
def rem_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    # clearing y for new text
    y=x[:]
    x.clear()
    return y

In [74]:
df['review']=df['review'].apply(rem_stopwords)

In [76]:
df

review  sentiment
9571   [movie, complexity, subtlety, makes, one, thou...          1
17463  [dolph, lundgren, stars, murray, wilson, alcoh...          0
32417  [quickie, tells, decadent, russian, mob, famil...          0
5827   [blatantly, made, tv, ripoff, black, widow, 19...          0
31252  [starters, would, like, say, fan, american, pi...          0
...                                                  ...        ...
27876  [really, week, go, oprah, remind, us, abused, ...          0
22244  [hello, went, movie, without, expectation, tho...          1
27931  [excellent, drama, 2, alienated, spoiled, punk...          1
10656  [seriously, find, anything, constituted, ratio...          0
9668   [sherman, hemsley, great, jeffersons, especial...          0

[10000 rows x 2 columns]

In [77]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

## APPLYING STEMMING 

In [78]:
y=[]
def stemming(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z
    

In [79]:
df['review']=df['review'].apply(stemming)

##  REJOINING THE LIST TO TEXT

In [80]:
def join_back(list_input):
    return " ".join(list_input)

In [81]:
df['review']=df['review'].apply(join_back)

In [82]:
df

review  sentiment
9571   movi complex subtleti make one thought provok ...          1
17463  dolph lundgren star murray wilson alcohol ex c...          0
32417  quicki tell decad russian mob famili live mali...          0
5827   blatantli made tv ripoff black widow 1987 even...          0
31252  starter would like say fan american pie seri e...          0
...                                                  ...        ...
27876  realli week go oprah remind us abus child make...          0
22244  hello went movi without expect though knew man...          1
27931  excel drama 2 alien spoil punk go afoul feder ...          1
10656  serious find anyth constitut ration human thou...          0
9668   sherman hemsley great jefferson especi famili ...          0

[10000 rows x 2 columns]

## CONVERTING TEXT DATA IN RWVIEWS TO NUM USING COUNT VECTOR CLASS

In [181]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2000)

In [151]:
X=df.iloc[:,0:1].values
X

array([['movi complex subtleti make one thought provok short film ever seen topic address ugli cynic time even macabr film remain beauti languag art camera angl gorgeou style skill recreat short stori name written master short stori tobia wolff wish spoil anyth movi go detail say movi magnific take pride well show import memori life top singl elus feel unexpect bliss movi volit creat feel main charact tom noonan felt word transform exist one impress feat'],
       ['dolph lundgren star murray wilson alcohol ex cop get involv serial killer kill sex brother murder wilson start investig find lot brother secret dull thriller lundgren mail perform movi flat letharg also anyon watch dolph lundgren movi anyth action'],
       ['quicki tell decad russian mob famili live malibu well frankli aw attempt drama worthi commentari jason leigh introduc mr mob guy pacif extermin huge letter plain sight back say west coast extermin eventu mob guy get suspici extermin bedroom duh anoth scene mr mobguy pl

In [182]:
X=cv.fit_transform(df['review']).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [183]:
X.shape

(10000, 2000)

In [184]:
y=df.iloc[:,-1].values
y

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

## TEST AND TRAINING DATA CREATION 

In [185]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [186]:
X_train.shape,y_train.shape


((8000, 2000), (8000,))

In [117]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [144]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()

## TRAINING GAUSSIAN NAIVE BAYES

In [187]:

gnb.fit(X_train,y_train)



GaussianNB()

In [228]:
np.mean(cross_val_score(gnb,X_train,y_train,cv=5,scoring='accuracy'))

0.731875

## ## TRAINING MULTINOMIAL NAIVE BAYES

In [188]:
mnb.fit(X_train,y_train)

MultinomialNB()

In [229]:
np.mean(cross_val_score(mnb,X_train,y_train,cv=5,scoring='accuracy'))

0.8355

## ## TRAINING BERNULLI NAIVE BAYES

In [189]:
bnb.fit(X_train,y_train)

BernoulliNB()

In [231]:
np.mean(cross_val_score(bnb,X_train,y_train,cv=10,scoring='accuracy'))

0.84475

In [190]:
ypred1=gnb.predict(X_test)
ypred2=bnb.predict(X_test)
ypred3=mnb.predict(X_test)

In [123]:
from sklearn.metrics import accuracy_score

## ACCURACY SCORE 
GNB=.72
BNB=.84
MNB=.85

<!-- HERE BEST PERFORMING IS MNB CHOOSING THIS AS MODEL -->

In [191]:
print('guassiannb',accuracy_score(y_test,ypred1))
print('bernoullinb',accuracy_score(y_test,ypred2))
print('multinomialb',accuracy_score(y_test,ypred3))

guassiannb 0.7295
bernoullinb 0.8485
multinomialb 0.8505


## PREDICTION USING ORIGINAL DATA BY GNB ,MNB,BNB

In [208]:
X[4]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [210]:
gnb.predict(X[4].reshape(1,-1))

array([0], dtype=int64)

In [211]:
bnb.predict(X[4].reshape(1,-1))

array([0], dtype=int64)

In [212]:
mnb.predict(X[4].reshape(1,-1))

array([0], dtype=int64)

In [209]:
y[4]

0

## ALSO COMPARING WITH OTHER MODEL LIKE RANDOM FOREST ,LOG REG
1.LOG REG

In [215]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [216]:
lg.fit(X_train,y_train)

C:\Users\deepe\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [217]:
from sklearn.model_selection import cross_val_score

In [219]:
np.mean(cross_val_score(lg,X_train,y_train,cv=5,scoring='accuracy'))

C:\Users\deepe\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\deepe\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

0.8283750000000001

In [221]:
lg.predict(X[23].reshape(1,-1))

array([1], dtype=int64)

##  RANDOM FOREST 

In [222]:
from sklearn.ensemble import RandomForestClassifier

In [224]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [225]:
np.mean(cross_val_score(rf,X_train,y_train,cv=5,scoring='accuracy'))

0.82925

In [227]:
rf.predict(X[4].reshape(1,-1))

array([0], dtype=int64)